export type Command = {
  cmd: string;
  desc: string;
  example?: string;
};

export type CommandSection = {
  title: string;
  commands: Command[];
};

export type AiToolCommandGuide = {
  id: string;
  name: string;
  subtitle: string;
  docsUrl: string;
  icon: string;
  sections: CommandSection[];
};

export const aiCommandTools: AiToolCommandGuide[] = [
  {
    id: "claude-code",
    name: "Claude Code",
    subtitle: "Anthropic 出品的 AI 编程助手 CLI",
    docsUrl: "https://code.claude.com/docs/zh-CN/commands",
    icon: "/ui-new/tool-icons/claude-code.png",
    sections: [
      {
        title: "会话与上下文",
        commands: [
          { cmd: "/clear [name]", desc: "使用空上下文开始新对话，旧对话仍可在 /resume 中恢复；别名 /reset、/new", example: "/clear 修复登录问题" },
          { cmd: "/compact [instructions]", desc: "总结当前对话以释放上下文，可附带本次压缩的关注点", example: "/compact 保留后端接口约束" },
          { cmd: "/context [all]", desc: "以网格查看上下文使用情况、容量警告和优化建议", example: "/context all" },
          { cmd: "/resume [session]", desc: "按 ID 或名称恢复对话，或打开会话选择器；别名 /continue", example: "/resume" },
          { cmd: "/branch [name]", desc: "从当前点创建会话分支，保留原始分支；默认别名 /fork", example: "/branch api-refactor" },
          { cmd: "/rewind", desc: "将对话或代码倒回到前一个点；别名 /checkpoint、/undo", example: "/rewind" },
          { cmd: "/rename [name]", desc: "重命名当前会话；不传名称时从历史自动生成", example: "/rename 支付回调修复" },
          { cmd: "/recap", desc: "生成当前会话的一行摘要", example: "/recap" },
          { cmd: "/export [filename]", desc: "将当前对话导出为纯文本，可直接写入指定文件", example: "/export notes.txt" },
          { cmd: "/copy [N]", desc: "复制最近一次或第 N 个最近的助手回复；有代码块时可选择复制范围", example: "/copy 2" },
          { cmd: "/btw <question>", desc: "提出一个不会加入主对话上下文的快速附加问题", example: "/btw 这个命令会改文件吗" },
          { cmd: "/goal [condition|clear]", desc: "设置多轮目标，让 Claude 持续工作直到满足条件；clear/stop/off 可取消", example: "/goal tests pass" },
          { cmd: "/plan [description]", desc: "直接进入 Plan Mode，可同时给出任务描述", example: "/plan fix the auth bug" },
        ],
      },
      {
        title: "配置、账户与权限",
        commands: [
          { cmd: "/help", desc: "显示帮助和可用命令", example: "/help" },
          { cmd: "/status", desc: "打开状态页，查看版本、模型、账户和连接性", example: "/status" },
          { cmd: "/config", desc: "打开设置界面，调整主题、模型、输出样式等；别名 /settings", example: "/config" },
          { cmd: "/login", desc: "登录 Anthropic 账户", example: "/login" },
          { cmd: "/logout", desc: "退出 Anthropic 账户", example: "/logout" },
          { cmd: "/model [model]", desc: "为当前会话设置模型；不带参数时打开选择器", example: "/model claude-opus-4-5" },
          { cmd: "/effort [level|auto]", desc: "设置模型工作量级别：low、medium、high、xhigh、max 或 auto", example: "/effort high" },
          { cmd: "/fast [on|off]", desc: "开启或关闭快速模式", example: "/fast on" },
          { cmd: "/permissions", desc: "管理工具权限的允许、询问和拒绝规则；别名 /allowed-tools", example: "/permissions" },
          { cmd: "/add-dir <path>", desc: "为当前会话添加可访问的工作目录", example: "/add-dir ../shared" },
          { cmd: "/privacy-settings", desc: "查看和更新隐私设置，适用于 Pro 和 Max 订阅者", example: "/privacy-settings" },
          { cmd: "/usage", desc: "显示会话成本、计划限制和活动统计；/cost、/stats 是别名", example: "/usage" },
          { cmd: "/usage-credits", desc: "配置额外使用额度；旧命令为 /extra-usage", example: "/usage-credits" },
          { cmd: "/upgrade", desc: "打开升级页面以切换到更高计划", example: "/upgrade" },
        ],
      },
      {
        title: "代码审查与变更",
        commands: [
          { cmd: "/diff", desc: "打开交互式差异查看器，查看未提交改动和每轮差异", example: "/diff" },
          { cmd: "/code-review [level] [--fix] [--comment] [target]", desc: "审阅当前差异，查找正确性问题和可清理项；可用 --fix 应用发现", example: "/code-review high --fix" },
          { cmd: "/simplify", desc: "等同于 /code-review --fix，用于应用简化和清理建议", example: "/simplify" },
          { cmd: "/review [PR]", desc: "在当前会话中本地审阅 pull request", example: "/review 123" },
          { cmd: "/security-review", desc: "分析当前分支待处理更改中的安全风险", example: "/security-review" },
          { cmd: "/ultrareview [PR]", desc: "在云沙箱中运行深度多 agent 代码审阅", example: "/ultrareview 123" },
          { cmd: "/autofix-pr [prompt]", desc: "启动网络版会话监视当前 PR，并在 CI 失败或收到评论时推送修复", example: "/autofix-pr only fix lint and type errors" },
          { cmd: "/pr-comments [PR]", desc: "旧版本用于获取 PR 评论；v2.1.91 起官方建议直接询问 Claude", example: "/pr-comments 123" },
          { cmd: "/batch <instruction>", desc: "将跨代码库的大型变更拆成独立单元，并在 worktree 中并行执行", example: "/batch migrate src/ from Solid to React" },
          { cmd: "/ultraplan <prompt>", desc: "在浏览器中起草并审阅 ultraplan，再远程执行或发回终端", example: "/ultraplan plan the payments migration" },
        ],
      },
      {
        title: "后台、云端与协作",
        commands: [
          { cmd: "/agents", desc: "管理 agent 配置", example: "/agents" },
          { cmd: "/background [prompt]", desc: "将当前会话分离为后台 agent 继续运行；别名 /bg", example: "/background keep fixing tests" },
          { cmd: "/tasks", desc: "列出并管理后台任务；也可用作 /bashes", example: "/tasks" },
          { cmd: "/stop", desc: "停止当前附加的后台会话；要只分离可用 /exit", example: "/stop" },
          { cmd: "/teleport", desc: "把网络版 Claude Code 会话拉入此终端；别名 /tp", example: "/teleport" },
          { cmd: "/remote-control", desc: "允许从 claude.ai 远程控制此本地会话；别名 /rc", example: "/remote-control" },
          { cmd: "/remote-env", desc: "为使用 --remote 启动的网络会话配置默认远程环境", example: "/remote-env" },
          { cmd: "/schedule [description]", desc: "创建、更新、列出或运行云端 routines；别名 /routines", example: "/schedule daily dependency audit" },
          { cmd: "/loop [interval] [prompt]", desc: "在会话保持打开时重复运行提示；别名 /proactive", example: "/loop 5m check if the deploy finished" },
          { cmd: "/web-setup", desc: "用本地 gh CLI 凭证连接 GitHub 到网络版 Claude Code", example: "/web-setup" },
          { cmd: "/install-github-app", desc: "为仓库设置 Claude GitHub Actions 应用", example: "/install-github-app" },
          { cmd: "/install-slack-app", desc: "安装 Claude Slack 应用并打开浏览器完成 OAuth", example: "/install-slack-app" },
        ],
      },
      {
        title: "项目初始化与扩展",
        commands: [
          { cmd: "/init", desc: "使用 CLAUDE.md 指南初始化项目；可用 CLAUDE_CODE_NEW_INIT=1 启用交互流程", example: "/init" },
          { cmd: "/memory", desc: "编辑 CLAUDE.md 内存文件，管理 auto-memory 和自动内存条目", example: "/memory" },
          { cmd: "/mcp", desc: "管理 MCP server 连接和 OAuth 身份验证", example: "/mcp" },
          { cmd: "/mcp__<server>__<prompt>", desc: "运行 MCP server 暴露的 prompt 命令", example: "/mcp__github__review_pr" },
          { cmd: "/plugin", desc: "管理 Claude Code plugins", example: "/plugin" },
          { cmd: "/reload-plugins", desc: "重新加载活跃 plugins，无需重启会话", example: "/reload-plugins" },
          { cmd: "/skills", desc: "列出可用 skills，可排序或隐藏菜单中的 skill", example: "/skills" },
          { cmd: "/reload-skills", desc: "重新扫描磁盘上的 skills 和命令目录", example: "/reload-skills" },
          { cmd: "/run", desc: "Skill：启动并驱动项目应用，观察真实运行结果", example: "/run" },
          { cmd: "/verify", desc: "Skill：构建、运行并观察应用来验证代码更改", example: "/verify" },
          { cmd: "/run-skill-generator", desc: "Skill：为项目生成 /run 与 /verify 所需的运行验证 skill", example: "/run-skill-generator" },
          { cmd: "/claude-api [migrate|managed-agents-onboard]", desc: "Skill：加载 Claude API 参考，支持迁移模型参数或创建 Managed Agent", example: "/claude-api migrate" },
          { cmd: "/fewer-permission-prompts", desc: "Skill：扫描历史工具调用并写入允许规则，减少只读权限提示", example: "/fewer-permission-prompts" },
        ],
      },
      {
        title: "诊断、界面与设备",
        commands: [
          { cmd: "/doctor", desc: "诊断并验证 Claude Code 安装和设置，可按 f 尝试修复问题", example: "/doctor" },
          { cmd: "/debug [description]", desc: "为当前会话启用调试日志并分析问题", example: "/debug terminal hangs after tool call" },
          { cmd: "/heapdump", desc: "写出 JavaScript 堆快照，用于诊断高内存使用", example: "/heapdump" },
          { cmd: "/feedback [report]", desc: "提交反馈、报告错误或分享对话；别名 /bug、/share", example: "/feedback login loop on Windows" },
          { cmd: "/release-notes", desc: "打开交互式版本选择器查看发布说明", example: "/release-notes" },
          { cmd: "/powerup", desc: "通过快速交互课程发现 Claude Code 功能", example: "/powerup" },
          { cmd: "/insights", desc: "生成会话分析报告，包括项目领域、交互模式和摩擦点", example: "/insights" },
          { cmd: "/team-onboarding", desc: "从使用历史生成团队入职指南", example: "/team-onboarding" },
          { cmd: "/terminal-setup", desc: "为 Shift+Enter 等快捷键配置终端设置", example: "/terminal-setup" },
          { cmd: "/keybindings", desc: "打开或创建快捷键配置文件", example: "/keybindings" },
          { cmd: "/ide", desc: "管理 IDE 集成并显示状态", example: "/ide" },
          { cmd: "/tui [default|fullscreen]", desc: "设置终端 UI 渲染器，可启用 fullscreen 渲染", example: "/tui fullscreen" },
          { cmd: "/focus", desc: "切换焦点视图，仅显示关键提示、工具摘要和最终响应", example: "/focus" },
          { cmd: "/scroll-speed", desc: "交互式调整鼠标滚轮滚动速度", example: "/scroll-speed" },
          { cmd: "/theme", desc: "更改颜色主题，支持 auto、自定义主题和插件主题", example: "/theme" },
          { cmd: "/color [color|default]", desc: "设置当前会话提示栏颜色", example: "/color cyan" },
          { cmd: "/statusline", desc: "配置 Claude Code 状态行", example: "/statusline" },
          { cmd: "/desktop", desc: "在 Claude Code Desktop 应用中继续当前会话；别名 /app", example: "/desktop" },
          { cmd: "/chrome", desc: "配置 Claude in Chrome 设置", example: "/chrome" },
          { cmd: "/mobile", desc: "显示二维码下载 Claude 移动应用；别名 /ios、/android", example: "/mobile" },
          { cmd: "/voice [hold|tap|off]", desc: "切换语音听写模式，需要 Claude.ai 账户", example: "/voice tap" },
        ],
      },
      {
        title: "其他与已移除命令",
        commands: [
          { cmd: "/exit", desc: "退出 CLI；附加到后台会话时会分离但不停止；别名 /quit", example: "/exit" },
          { cmd: "/sandbox", desc: "切换 sandbox mode，仅在支持的平台可用", example: "/sandbox" },
          { cmd: "/hooks", desc: "查看工具事件的 hook 配置", example: "/hooks" },
          { cmd: "/setup-bedrock", desc: "配置 Amazon Bedrock 身份验证、区域和模型固定", example: "/setup-bedrock" },
          { cmd: "/setup-vertex", desc: "配置 Google Vertex AI 身份验证、项目、区域和模型固定", example: "/setup-vertex" },
          { cmd: "/passes", desc: "与朋友分享一周免费的 Claude Code；仅符合条件账户可见", example: "/passes" },
          { cmd: "/radio", desc: "在浏览器中打开 Claude FM lo-fi 电台，或打印流 URL", example: "/radio" },
          { cmd: "/stickers", desc: "订购 Claude Code 贴纸", example: "/stickers" },
          { cmd: "/vim", desc: "v2.1.92 起已移除；请用 /config 的编辑器模式切换", example: "/config" },
        ],
      },
    ],
  },
  {
    id: "codex",
    name: "Codex",
    subtitle: "OpenAI 出品的本地、桌面与云端 AI 编程代理",
    docsUrl: "https://developers.openai.com/codex/cli",
    icon: "/ui-new/tool-icons/codex.png",
    sections: [
      {
        title: "CLI 常用命令",
        commands: [
          { cmd: "codex", desc: "启动终端交互界面。可以直接带一句任务描述，也可以进入后再输入", example: 'codex "解释这个仓库的结构"' },
          { cmd: "codex app", desc: "打开 Codex 桌面应用。macOS 可以直接带工作区路径，Windows 会打印要打开的路径", example: "codex app D:\\my-work\\moyu-base" },
          { cmd: "codex exec", desc: "非交互模式跑一次任务，适合脚本、CI 或把结果输出成日志；别名 codex e", example: 'codex exec "修复 lint 报错并说明改动"' },
          { cmd: "codex resume", desc: "恢复之前的交互会话。默认按当前目录找最近会话，也可以指定会话 ID", example: "codex resume --last" },
          { cmd: "codex fork", desc: "把旧会话分叉成一个新线程，适合尝试另一种实现思路又不想丢掉原对话", example: "codex fork <session-id>" },
          { cmd: "codex apply", desc: "把 Codex Cloud 任务生成的最新 diff 应用到本地工作区；别名 codex a", example: "codex apply" },
          { cmd: "codex update", desc: "检查并更新 Codex CLI。是否支持自更新取决于当前安装方式", example: "codex update" },
          { cmd: "codex completion", desc: "生成 Bash、Zsh、Fish 或 PowerShell 的命令补全脚本", example: "codex completion powershell" },
        ],
      },
      {
        title: "CLI 全局选项",
        commands: [
          { cmd: "--model, -m <model>", desc: "本次运行临时指定模型，不改你的默认配置", example: "codex -m gpt-5.1-codex" },
          { cmd: "--sandbox, -s <policy>", desc: "控制 Codex 执行命令时能碰哪些文件：只读、工作区可写，或完全放开", example: "codex -s workspace-write" },
          { cmd: "--ask-for-approval, -a <mode>", desc: "设置什么时候需要你点头。常用 on-request；自动化场景才考虑 never", example: "codex -a on-request" },
          { cmd: "--cd, -C <path>", desc: "启动前先切到指定目录，省得你手动 cd", example: "codex -C D:\\my-work\\moyu-base" },
          { cmd: "--config, -c <key=value>", desc: "临时覆盖配置项。能按 JSON 解析就按 JSON，否则按普通字符串处理", example: 'codex -c model="gpt-5.1-codex"' },
          { cmd: "--add-dir <path>", desc: "把额外目录加入本次可访问范围，需要跨目录看代码时很有用", example: "codex --add-dir ../shared" },
          { cmd: "--image, -i <path>", desc: "把截图、设计稿或报错图片一起发给 Codex", example: "codex -i ./bug.png" },
          { cmd: "--search", desc: "开启实时联网搜索，而不是只用缓存结果", example: 'codex --search "查一下这个库最新迁移方式"' },
          { cmd: "--remote <url>", desc: "把终端界面连到远程 app-server，主要给远程开发或协议调试用", example: "codex --remote ws://127.0.0.1:9000" },
          { cmd: "--yolo", desc: "跳过审批和沙箱。风险很高，只适合已经隔离好的临时环境", example: "codex --yolo" },
        ],
      },
      {
        title: "CLI 管理与扩展",
        commands: [
          { cmd: "codex login", desc: "登录 Codex，支持 ChatGPT OAuth、设备登录、API key 或从 stdin 传 access token", example: "codex login" },
          { cmd: "codex logout", desc: "清掉本机保存的登录凭据，公用电脑上用完建议执行", example: "codex logout" },
          { cmd: "codex mcp", desc: "管理 MCP server：查看、添加、删除或做 OAuth 授权", example: "codex mcp list" },
          { cmd: "codex mcp-server", desc: "把 Codex 自己作为 MCP server 暴露给其他工具调用", example: "codex mcp-server" },
          { cmd: "codex features", desc: "查看功能开关，并把启用或禁用结果写进 config.toml", example: "codex features enable goals" },
          { cmd: "codex plugin marketplace", desc: "管理插件市场来源，可以添加、列出、更新或移除 Git / 本地市场", example: "codex plugin marketplace add owner/repo" },
          { cmd: "codex app-server", desc: "启动本地 app server，供桌面端、远程控制或调试客户端连接", example: "codex app-server --listen 127.0.0.1:9000" },
          { cmd: "codex remote-control", desc: "确保本地 app-server 守护进程已启用远程控制能力", example: "codex remote-control" },
          { cmd: "codex sandbox", desc: "用 Codex 内部同款沙箱策略运行任意命令，方便单独验证权限边界", example: 'codex sandbox -- echo "hello"' },
          { cmd: "codex execpolicy", desc: "测试某条命令会被执行策略放行、询问还是拦截", example: 'codex execpolicy check "npm test"' },
          { cmd: "codex debug models", desc: "打印 Codex 看到的原始模型列表，排查模型选择器问题时用", example: "codex debug models" },
        ],
      },
      {
        title: "CLI 斜杠命令",
        commands: [
          { cmd: "/permissions", desc: "调整 Codex 能自动做什么、哪些动作必须先问你", example: "/permissions" },
          { cmd: "/model", desc: "切换当前会话使用的模型和可用的推理强度", example: "/model" },
          { cmd: "/status", desc: "查看当前模型、审批策略、可写目录、上下文余量等会话状态", example: "/status" },
          { cmd: "/compact", desc: "把长对话压缩成摘要，腾出上下文空间继续干活", example: "/compact" },
          { cmd: "/clear", desc: "清空终端显示并开始一段新聊天，适合换任务时重来", example: "/clear" },
          { cmd: "/new", desc: "在同一个 CLI 会话里开一段新对话，不必退出重进", example: "/new" },
          { cmd: "/resume", desc: "从会话列表里恢复之前的对话", example: "/resume" },
          { cmd: "/fork", desc: "把当前对话分叉成新线程，方便试另一条路线", example: "/fork" },
          { cmd: "/side", desc: "开一个临时旁路对话，问个小问题又不打乱主线", example: "/side" },
          { cmd: "/plan", desc: "进入计划模式，先让 Codex 拆解步骤再动手", example: "/plan 修复登录状态丢失" },
          { cmd: "/goal", desc: "设置、暂停、恢复或清除一个持续目标，让 Codex 围着目标推进", example: "/goal 所有测试通过" },
          { cmd: "/review", desc: "让 Codex 审查当前工作区改动，相当于请它再看一遍", example: "/review" },
          { cmd: "/diff", desc: "查看 Git diff，包括还没被 Git 跟踪的新文件", example: "/diff" },
          { cmd: "/copy", desc: "复制最近一次完成的 Codex 输出，也可以用 Ctrl+O", example: "/copy" },
          { cmd: "/raw", desc: "切换原始回滚显示，长输出复制起来更干净", example: "/raw" },
        ],
      },
      {
        title: "CLI 斜杠命令：上下文与扩展",
        commands: [
          { cmd: "/ide", desc: "把 IDE 里打开的文件、当前选区等上下文带进下一次提问", example: "/ide" },
          { cmd: "/mention", desc: "把指定文件或文件夹附加到对话里，让 Codex 重点看它", example: "/mention frontend/src/lib/api.ts" },
          { cmd: "/mcp", desc: "查看当前配置的 MCP 工具；加 verbose 可看 server 细节", example: "/mcp verbose" },
          { cmd: "/apps", desc: "浏览可用连接器，并把某个 app 作为 $app-slug 插入提示词", example: "/apps" },
          { cmd: "/plugins", desc: "浏览已安装或可发现的插件，管理插件可用性", example: "/plugins" },
          { cmd: "/skills", desc: "浏览并使用 skills，让 Codex 按某类任务的专业流程工作", example: "/skills" },
          { cmd: "/hooks", desc: "查看生命周期 hooks，确认、信任或禁用即将运行的 hook", example: "/hooks" },
          { cmd: "/memories", desc: "管理记忆注入和记忆生成，不用离开 TUI", example: "/memories" },
          { cmd: "/init", desc: "在当前目录生成 AGENTS.md 脚手架，记录仓库规则和长期指令", example: "/init" },
          { cmd: "/agent", desc: "切换当前活跃的 agent 线程，查看或继续子代理任务", example: "/agent" },
          { cmd: "/ps", desc: "查看实验性后台终端和最近输出", example: "/ps" },
          { cmd: "/stop", desc: "停止当前会话启动的所有后台终端", example: "/stop" },
        ],
      },
      {
        title: "CLI 体验与退出",
        commands: [
          { cmd: "/fast", desc: "在模型目录支持时切换 Fast 服务层，或查看当前线程是否在用 Fast", example: "/fast" },
          { cmd: "/personality", desc: "调整回复风格，比如更简洁、更解释型或更协作", example: "/personality" },
          { cmd: "/keymap", desc: "查看并持久化 TUI 快捷键绑定", example: "/keymap" },
          { cmd: "/vim", desc: "切换输入框的 Vim 编辑模式", example: "/vim" },
          { cmd: "/experimental", desc: "打开或关闭实验功能，比如 CLI 里的 subagents", example: "/experimental" },
          { cmd: "/approve", desc: "对最近一次被自动审查拒绝的操作批准重试一次", example: "/approve" },
          { cmd: "/sandbox-add-read-dir", desc: "Windows 下给沙箱额外开放一个只读目录", example: "/sandbox-add-read-dir C:\\logs" },
          { cmd: "/feedback", desc: "把日志发给 Codex 维护者，用于报告问题或提供诊断信息", example: "/feedback" },
          { cmd: "/exit", desc: "退出 CLI；等同于 /quit", example: "/exit" },
          { cmd: "/quit", desc: "退出当前 Codex 终端会话", example: "/quit" },
        ],
      },
      {
        title: "Codex app 快捷键",
        commands: [
          { cmd: "Cmd + Shift + P / Cmd + K", desc: "打开命令菜单，想找设置或动作时先按这个" },
          { cmd: "Cmd + ,", desc: "打开设置" },
          { cmd: "Cmd + /", desc: "打开或查看键盘快捷键" },
          { cmd: "Cmd + O", desc: "打开文件夹或工作区" },
          { cmd: "Cmd + [ / Cmd + ]", desc: "前进、后退导航" },
          { cmd: "Cmd + B", desc: "显示或隐藏侧边栏" },
          { cmd: "Cmd + Option + B", desc: "显示或隐藏 diff 面板" },
          { cmd: "Cmd + J", desc: "显示或隐藏终端" },
          { cmd: "Ctrl + L", desc: "清空终端显示" },
          { cmd: "Cmd + N / Cmd + Shift + O", desc: "新建 thread" },
          { cmd: "Cmd + F", desc: "在当前 thread 里搜索" },
          { cmd: "Cmd + Shift + [ / ]", desc: "切换上一个或下一个 thread" },
          { cmd: "Ctrl + M", desc: "语音输入" },
        ],
      },
      {
        title: "Codex app 斜杠与链接",
        commands: [
          { cmd: "/feedback", desc: "打开反馈窗口，可选择附带日志", example: "/feedback" },
          { cmd: "/goal", desc: "设置一个持续目标，让 Codex 一直围着目标推进；通常先用 /plan 打磨目标", example: "/goal 完成命令页内容校对" },
          { cmd: "/mcp", desc: "打开 MCP 状态，查看已连接的 server", example: "/mcp" },
          { cmd: "/plan", desc: "切换到多步骤规划模式", example: "/plan" },
          { cmd: "/review", desc: "进入代码审查模式，检查未提交改动或和基准分支对比", example: "/review" },
          { cmd: "/status", desc: "显示 thread ID、上下文使用量和速率限制", example: "/status" },
          { cmd: "codex://threads/new", desc: "打开一个新的本地 thread", example: "codex://threads/new?prompt=检查这个仓库" },
          { cmd: "codex://settings", desc: "打开 Codex app 设置页", example: "codex://settings" },
          { cmd: "codex://skills", desc: "打开 Skills 页面", example: "codex://skills" },
          { cmd: "codex://automations", desc: "打开 Automations，并进入创建流程", example: "codex://automations" },
          { cmd: "codex://plugins/<plugin-id>", desc: "打开指定插件详情页", example: "codex://plugins/openai-developers@openai-curated" },
        ],
      },
    ],
  },
  {
    id: "cursor",
    name: "Cursor",
    subtitle: "基于 VS Code 的 AI 编程编辑器与命令行代理",
    docsUrl: "https://cursor.com/docs/cli/overview",
    icon: "/ui-new/tool-icons/cursor.png",
    sections: [
      {
        title: "Cursor CLI",
        commands: [
          { cmd: "cursor-agent", desc: "启动 Cursor 的终端代理，在当前目录里对话、读代码和改文件", example: "cursor-agent" },
          { cmd: 'cursor-agent -p "..."', desc: "非交互执行一条任务，适合脚本、CI 或把结果输出给别的命令", example: 'cursor-agent -p "review this PR"' },
          { cmd: "cursor-agent resume", desc: "恢复之前的会话，默认按当前项目找最近记录", example: "cursor-agent resume" },
          { cmd: "cursor-agent ls", desc: "列出本机保存的 Cursor Agent 会话", example: "cursor-agent ls" },
          { cmd: "cursor-agent login", desc: "登录 Cursor 账户，让 CLI 复用你的订阅和模型配置", example: "cursor-agent login" },
          { cmd: "cursor-agent logout", desc: "退出本机 CLI 登录状态", example: "cursor-agent logout" },
          { cmd: "cursor-agent mcp", desc: "管理 MCP server，给 Agent 接入外部工具和数据源", example: "cursor-agent mcp list" },
        ],
      },
      {
        title: "CLI 常用选项",
        commands: [
          { cmd: "--model <model>", desc: "指定本次使用的模型，不改默认设置", example: "cursor-agent --model gpt-5.1-codex" },
          { cmd: "--force", desc: "允许 Agent 在需要时更主动地执行操作；只在你信任当前工作区时使用", example: "cursor-agent --force" },
          { cmd: "--output-format <format>", desc: "切换输出格式，自动化场景常用 json 或 stream-json", example: 'cursor-agent -p "status" --output-format json' },
          { cmd: "--print, -p", desc: "打印模式：执行提示后输出结果并退出", example: 'cursor-agent -p "summarize changes"' },
          { cmd: "--resume <id>", desc: "按会话 ID 恢复指定对话", example: "cursor-agent --resume abc123" },
          { cmd: "--help", desc: "查看当前版本支持的命令和参数", example: "cursor-agent --help" },
        ],
      },
      {
        title: "编辑器上下文",
        commands: [
          { cmd: "@Files & Folders", desc: "把某个文件或目录明确加入 Chat 上下文，适合让 AI 只看你关心的范围", example: "@frontend/src/lib/api.ts" },
          { cmd: "@Code", desc: "引用当前选中的代码片段，让回答更聚焦", example: "@Code 这段为什么会重复请求" },
          { cmd: "@Git", desc: "引用当前 diff、提交或分支信息，适合做变更解释和审查", example: "@Git 总结这次改动" },
          { cmd: "@Docs", desc: "引用已索引的官方文档，回答框架或库用法时更可靠", example: "@Docs Astro middleware 怎么写" },
          { cmd: "@Web", desc: "联网搜索最新资料，适合查版本变化和新文档", example: "@Web Cursor CLI 最新参数" },
          { cmd: "@Codebase", desc: "在整个代码库做语义检索，找调用链、实现位置和相关文件", example: "@Codebase 登录状态在哪里保存" },
        ],
      },
      {
        title: "项目规则与斜杠命令",
        commands: [
          { cmd: ".cursor/rules/*.mdc", desc: "项目级规则文件，写技术栈、目录边界、测试要求和团队约定", example: ".cursor/rules/frontend.mdc" },
          { cmd: "AGENTS.md", desc: "Cursor Agent 会读取的代理说明文件，适合和 Codex、Claude Code 共用项目规范", example: "AGENTS.md" },
          { cmd: "/Generate Cursor Rules", desc: "根据当前项目生成或补全 Cursor Rules", example: "/Generate Cursor Rules" },
          { cmd: "/Bug Finder", desc: "让 Cursor 从当前变更里找潜在 bug 和风险点", example: "/Bug Finder" },
          { cmd: "Custom Modes", desc: "为不同任务配置不同模型、工具权限和提示词，例如 Review、Plan、Implement", example: "Review mode" },
        ],
      },
      {
        title: "快捷入口",
        commands: [
          { cmd: "Ctrl + K", desc: "行内 AI 编辑（选中代码后触发）" },
          { cmd: "Ctrl + L", desc: "打开 Chat 侧边栏" },
          { cmd: "Ctrl + I", desc: "打开 Agent/Composer 类的多文件编辑入口，不同版本名称略有差异" },
          { cmd: "Ctrl + Shift + L", desc: "把选中代码送进 Chat 上下文" },
          { cmd: "Escape", desc: "关闭 AI 建议面板" },
          { cmd: "Tab", desc: "接受 AI 代码补全建议" },
        ],
      },
    ],
  },
  {
    id: "cherry-studio",
    name: "Cherry Studio",
    subtitle: "开源桌面 AI 助手与多模型工作台",
    docsUrl: "https://docs.cherry-ai.com/advanced-basic/code-tools-shi-yong-jiao-cheng",
    icon: "/ui-new/tool-icons/cherry-studio.png",
    sections: [
      {
        title: "桌面端入口",
        commands: [
          { cmd: "Providers", desc: "配置 OpenAI、Anthropic、Gemini、Ollama 等模型服务商，一个客户端集中管理", example: "Settings → Providers" },
          { cmd: "Assistants", desc: "创建不同角色的助手，按写作、翻译、编程、分析等场景分开使用", example: "New Assistant" },
          { cmd: "Topics", desc: "用话题管理对话，把同一项目或同一问题串起来", example: "New Topic" },
          { cmd: "Knowledge Base", desc: "导入文档、网页或本地资料，做可检索的私有知识库", example: "Knowledge → Add" },
          { cmd: "Translate", desc: "调用模型做翻译和润色，适合日常文本处理", example: "Tools → Translate" },
        ],
      },
      {
        title: "Code Tools",
        commands: [
          { cmd: "Claude Code", desc: "在 Cherry Studio 里配置并启动 Claude Code，适合把桌面模型管理和终端编程工具连起来", example: "Settings → Code Tools → Claude Code" },
          { cmd: "Gemini CLI", desc: "配置 Gemini CLI 路径和环境变量，从桌面端发起终端代理任务", example: "Settings → Code Tools → Gemini CLI" },
          { cmd: "Qwen Code", desc: "接入 Qwen Code，适合使用通义千问生态的本地编程流程", example: "Settings → Code Tools → Qwen Code" },
          { cmd: "OpenAI Codex", desc: "配置 Codex CLI，让 Cherry Studio 能拉起 OpenAI 的本地编程代理", example: "Settings → Code Tools → OpenAI Codex" },
        ],
      },
      {
        title: "MCP 与扩展",
        commands: [
          { cmd: "MCP Servers", desc: "添加 MCP server，把文件系统、浏览器、数据库、GitHub 等工具接进模型", example: "Settings → MCP Servers" },
          { cmd: "MCP Marketplace", desc: "从市场安装常见 MCP 工具，减少手写配置", example: "MCP → Marketplace" },
          { cmd: "Web Search", desc: "配置联网搜索能力，让回答能参考最新网页资料", example: "Settings → Web Search" },
          { cmd: "Artifacts", desc: "在对话中预览代码、图表或结构化结果，适合边聊边看产物", example: "Enable Artifacts" },
        ],
      },
      {
        title: "本地与同步",
        commands: [
          { cmd: "Data Settings", desc: "管理本地数据、备份与迁移，换电脑前建议先导出", example: "Settings → Data" },
          { cmd: "Theme", desc: "切换界面主题和显示偏好", example: "Settings → Appearance" },
          { cmd: "Shortcuts", desc: "查看或修改快捷键，提高桌面端常用操作效率", example: "Settings → Shortcuts" },
          { cmd: "Proxy", desc: "配置代理网络，解决部分模型服务连接问题", example: "Settings → Proxy" },
        ],
      },
    ],
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    subtitle: "Google Gemini 的开源终端 AI 代理",
    docsUrl: "https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/cli-reference.md",
    icon: "/ui-new/tool-icons/gemini-cli.png",
    sections: [
      {
        title: "终端入口",
        commands: [
          { cmd: "gemini", desc: "进入交互式终端，适合边问边改、逐步推进任务", example: "gemini" },
          { cmd: 'gemini -p "query"', desc: "非交互执行一次提示词，适合脚本、管道和快速问答", example: 'gemini -p "summarize README.md"' },
          { cmd: 'gemini "query"', desc: "先带着问题启动，再继续留在交互会话里", example: 'gemini "explain this project"' },
          { cmd: "cat file | gemini", desc: "把文件或命令输出通过管道交给 Gemini 处理；PowerShell 可用 Get-Content", example: "Get-Content logs.txt | gemini" },
          { cmd: 'gemini -i "query"', desc: "先执行这条提示词，然后继续进入交互模式", example: 'gemini -i "这个项目主要做什么"' },
          { cmd: 'gemini -r "latest"', desc: "恢复最近一次会话，也可以指定 session id", example: 'gemini -r "latest" "继续检查类型错误"' },
          { cmd: "gemini update", desc: "更新 Gemini CLI 到最新版本", example: "gemini update" },
        ],
      },
      {
        title: "常用选项",
        commands: [
          { cmd: "--model, -m <model>", desc: "指定本次使用的模型；auto/pro 适合复杂任务，flash 更快，flash-lite 更轻量", example: "gemini -m flash" },
          { cmd: "--prompt, -p <text>", desc: "把提示词作为参数传入，并强制非交互模式", example: 'gemini -p "列出这个仓库的风险点"' },
          { cmd: "--worktree, -w <name>", desc: "在新的 git worktree 中启动，适合隔离大改动或多路线尝试", example: "gemini -w login-fix" },
          { cmd: "--sandbox, -s", desc: "用沙箱环境运行，减少工具误操作的风险", example: "gemini --sandbox" },
          { cmd: "--approval-mode <mode>", desc: "控制工具调用审批方式：default、auto_edit、yolo 或 plan", example: "gemini --approval-mode plan" },
          { cmd: "--include-directories <path>", desc: "把额外目录加入当前工作区上下文", example: "gemini --include-directories ../shared" },
          { cmd: "--output-format <format>", desc: "设置输出格式：text、json 或 stream-json", example: 'gemini -p "status" --output-format json' },
        ],
      },
      {
        title: "交互内命令",
        commands: [
          { cmd: "/help", desc: "显示交互模式下可用命令和帮助说明", example: "/help" },
          { cmd: "/quit", desc: "退出当前交互会话", example: "/quit" },
          { cmd: "/memory reload", desc: "重新加载 GEMINI.md 等上下文文件", example: "/memory reload" },
          { cmd: "/mcp reload", desc: "重启并重新加载 MCP server", example: "/mcp reload" },
          { cmd: "/commands list", desc: "列出当前可用的自定义斜杠命令", example: "/commands list" },
          { cmd: "/commands reload", desc: "重新加载自定义斜杠命令", example: "/commands reload" },
          { cmd: "/extensions reload", desc: "重新加载所有启用的扩展", example: "/extensions reload" },
          { cmd: "/skills reload", desc: "重新扫描并加载磁盘上的 agent skills", example: "/skills reload" },
        ],
      },
      {
        title: "扩展、MCP 与 Skills",
        commands: [
          { cmd: "gemini extensions list", desc: "查看已安装扩展", example: "gemini extensions list" },
          { cmd: "gemini extensions install <source>", desc: "从 Git URL 或本地路径安装扩展", example: "gemini extensions install https://github.com/user/my-extension" },
          { cmd: "gemini extensions update --all", desc: "更新全部扩展", example: "gemini extensions update --all" },
          { cmd: "gemini mcp add <name> <command>", desc: "添加 stdio 类型的 MCP server", example: "gemini mcp add github npx -y @modelcontextprotocol/server-github" },
          { cmd: "gemini mcp list", desc: "列出所有已配置的 MCP server", example: "gemini mcp list" },
          { cmd: "gemini skills list", desc: "列出已发现的 agent skills", example: "gemini skills list" },
          { cmd: "gemini skills install <source>", desc: "从 Git、路径或文件安装 skill", example: "gemini skills install https://github.com/u/repo" },
        ],
      },
    ],
  },
  {
    id: "cline",
    name: "Cline",
    subtitle: "VS Code 中的开源 AI 编程代理",
    docsUrl: "https://docs.cline.bot/core-workflows/using-commands",
    icon: "/ui-new/tool-icons/cline.png",
    sections: [
      {
        title: "内置斜杠命令",
        commands: [
          { cmd: "/newtask", desc: "把当前对话里真正有用的计划、文件和进度整理出来，带到一个干净的新任务里", example: "/newtask" },
          { cmd: "/smol", desc: "压缩当前对话历史，保留关键上下文；别名是 /compact", example: "/smol" },
          { cmd: "/newrule", desc: "创建 .clinerules 规则文件，让 Cline 记住你的沟通方式、代码规范和项目偏好", example: "/newrule" },
          { cmd: "/deep-planning", desc: "先调查代码库、追问需求并生成 implementation_plan.md，再进入实现任务", example: "/deep-planning" },
          { cmd: "/explain-changes", desc: "解释 Git diff，适合看不懂改动、接手代码或做 review；仅 VS Code 可用", example: "/explain-changes" },
          { cmd: "/reportbug", desc: "收集诊断信息并辅助提交问题反馈", example: "/reportbug" },
        ],
      },
      {
        title: "Skills 命令",
        commands: [
          { cmd: "/", desc: "在聊天输入框输入斜杠，会弹出可用命令和已启用 skills", example: "/" },
          { cmd: "/<skill-name>", desc: "直接调用某个已启用 skill，让 Cline 按对应 SKILL.md 的流程处理任务", example: "/aws-deploy" },
          { cmd: "/newrule + skill", desc: "把重复出现的团队偏好沉淀成规则，再配合 skill 做专门任务", example: "/newrule" },
        ],
      },
    ],
  },
  {
    id: "continue",
    name: "Continue",
    subtitle: "开源 AI 代码助手与 CLI",
    docsUrl: "https://docs.continue.dev/cli/tui-mode",
    icon: "/ui-new/tool-icons/continue.png",
    sections: [
      {
        title: "CLI 与上下文",
        commands: [
          { cmd: "cn", desc: "启动 Continue 的交互式终端会话，底层使用和 IDE 插件一致的 agent", example: "cn" },
          { cmd: "@<file-or-dir>", desc: "把文件或目录明确塞进上下文，让 agent 针对它分析或修改", example: "@src/auth/middleware.ts 为什么会拒绝有效 token?" },
          { cmd: "cn --resume", desc: "恢复最近一次会话，继续沿用之前的完整对话历史", example: "cn --resume" },
          { cmd: "/resume", desc: "在交互会话里恢复之前的聊天", example: "/resume" },
        ],
      },
      {
        title: "斜杠命令",
        commands: [
          { cmd: "/help", desc: "显示帮助信息和键盘快捷键", example: "/help" },
          { cmd: "/clear", desc: "清空当前聊天历史，适合换任务时重新开始", example: "/clear" },
          { cmd: "/login", desc: "登录 Continue 账户", example: "/login" },
          { cmd: "/logout", desc: "退出当前账户", example: "/logout" },
          { cmd: "/update", desc: "更新 Continue CLI", example: "/update" },
          { cmd: "/whoami", desc: "查看当前登录的是哪个账户", example: "/whoami" },
          { cmd: "/info", desc: "显示会话信息，包括 token 使用量和成本", example: "/info" },
          { cmd: "/model", desc: "在已配置的聊天模型之间切换", example: "/model" },
          { cmd: "/config", desc: "切换配置或组织", example: "/config" },
          { cmd: "/mcp", desc: "管理 MCP server 连接", example: "/mcp" },
          { cmd: "/init", desc: "为当前项目创建 AGENTS.md", example: "/init" },
          { cmd: "/compact", desc: "把聊天历史总结成更紧凑的上下文", example: "/compact" },
          { cmd: "/fork", desc: "从当前历史分叉出一条新会话", example: "/fork" },
          { cmd: "/title / /rename", desc: "设置或重命名当前会话标题", example: "/rename 支付问题排查" },
          { cmd: "/jobs", desc: "列出后台任务", example: "/jobs" },
          { cmd: "/exit", desc: "退出聊天", example: "/exit" },
        ],
      },
      {
        title: "远程环境",
        commands: [
          { cmd: "/diff", desc: "连接远程环境时可用，用来查看远程变更差异", example: "/diff" },
          { cmd: "/apply", desc: "连接远程环境时可用，用来应用远程改动", example: "/apply" },
          { cmd: "~/.continue/permissions.yaml", desc: "保存工具权限策略，常见选择是本次允许、以后不再问或拒绝", example: "~/.continue/permissions.yaml" },
        ],
      },
    ],
  },
  {
    id: "openhands",
    name: "OpenHands",
    subtitle: "All Hands AI 的开源软件开发代理",
    docsUrl: "https://docs.openhands.dev/openhands/usage/cli/command-reference",
    icon: "/ui-new/tool-icons/openhands.png",
    sections: [
      {
        title: "CLI 入口",
        commands: [
          { cmd: "openhands", desc: "启动 OpenHands CLI，在当前终端里开始一个开发代理会话", example: "openhands" },
          { cmd: "openhands --help", desc: "查看 CLI 的完整参数和用法", example: "openhands --help" },
          { cmd: "openhands serve", desc: "启动本地 OpenHands 服务端，用于 Web UI 或本地服务模式", example: "openhands serve" },
          { cmd: "openhands login", desc: "登录 OpenHands Cloud 或配置云端访问", example: "openhands login" },
          { cmd: "openhands --override-with-envs", desc: "临时用环境变量覆盖模型配置，不写入本地配置文件", example: "openhands --override-with-envs" },
        ],
      },
      {
        title: "配置与模型",
        commands: [
          { cmd: "LLM_API_KEY", desc: "设置模型供应商 API key", example: "$env:LLM_API_KEY='your-api-key'" },
          { cmd: "LLM_MODEL", desc: "临时指定模型；配合 --override-with-envs 生效", example: "$env:LLM_MODEL='gpt-4o'" },
          { cmd: "LLM_BASE_URL", desc: "使用自定义模型网关或兼容 OpenAI 的服务地址", example: "$env:LLM_BASE_URL='https://api.example.com/v1'" },
          { cmd: "~/.openhands/agent_settings.json", desc: "保存 LLM 配置和 agent 设置", example: "~/.openhands/agent_settings.json" },
          { cmd: "~/.openhands/mcp.json", desc: "保存 MCP server 配置", example: "~/.openhands/mcp.json" },
        ],
      },
      {
        title: "TUI 快捷动作",
        commands: [
          { cmd: "Ctrl + P", desc: "打开命令面板；官方文档里的模型设置流程也从这里进入" },
          { cmd: "Settings", desc: "在命令面板里进入设置，选择模型供应商和模型" },
          { cmd: "MCP", desc: "查看 MCP server 配置" },
          { cmd: "History", desc: "打开或关闭会话历史面板" },
          { cmd: "Plan", desc: "查看 agent 当前计划" },
          { cmd: "Screenshot", desc: "截取当前界面截图" },
          { cmd: "Quit", desc: "退出应用" },
        ],
      },
    ],
  },
  {
    id: "aider",
    name: "Aider",
    subtitle: "终端里的 AI 结对编程工具",
    docsUrl: "https://aider.chat/docs/usage/commands.html",
    icon: "/ui-new/tool-icons/aider.png",
    sections: [
      {
        title: "文件与上下文",
        commands: [
          { cmd: "/add", desc: "把文件加入聊天，让 aider 可以编辑或认真审阅它们", example: "/add src/app.py tests/test_app.py" },
          { cmd: "/read-only", desc: "把文件作为只读参考加入上下文，适合放规范、日志或外部代码", example: "/read-only README.md" },
          { cmd: "/drop", desc: "从当前聊天里移除文件，释放上下文空间", example: "/drop src/legacy.py" },
          { cmd: "/ls", desc: "列出 aider 已知文件，并标出哪些已经加入聊天", example: "/ls" },
          { cmd: "/map", desc: "打印当前仓库 map，快速了解代码结构", example: "/map" },
          { cmd: "/copy-context", desc: "把当前聊天上下文复制成 Markdown，方便贴到网页模型或 issue 里", example: "/copy-context" },
        ],
      },
      {
        title: "工作模式",
        commands: [
          { cmd: "/ask", desc: "只问代码库问题，不改文件；不带参数时切到 ask 模式", example: "/ask 认证流程在哪里" },
          { cmd: "/code", desc: "要求 aider 修改代码；不带参数时切到 code 模式", example: "/code 修复登录过期问题" },
          { cmd: "/architect", desc: "进入 architect/editor 双模型模式，先设计再落地", example: "/architect 设计缓存重构方案" },
          { cmd: "/chat-mode", desc: "切换到新的聊天模式", example: "/chat-mode ask" },
          { cmd: "/context", desc: "进入 context 模式，查看相关上下文和周边代码", example: "/context" },
          { cmd: "/editor", desc: "打开外部编辑器写一段更长的提示词；/edit 是别名", example: "/editor" },
        ],
      },
      {
        title: "变更与验证",
        commands: [
          { cmd: "/diff", desc: "显示自上次消息以来的改动 diff", example: "/diff" },
          { cmd: "/commit", desc: "提交本轮或外部产生的仓库改动，可附带 commit message", example: "/commit fix auth timeout" },
          { cmd: "/undo", desc: "撤销 aider 刚刚创建的最后一次 git commit", example: "/undo" },
          { cmd: "/run", desc: "运行 shell 命令，可选择把输出加入聊天；! 是别名", example: "/run pytest -q" },
          { cmd: "/test", desc: "运行测试命令，失败时把输出加入聊天供 aider 修", example: "/test pytest -q" },
          { cmd: "/lint", desc: "对聊天中的文件或所有 dirty 文件执行 lint 并尝试修复", example: "/lint ruff check ." },
        ],
      },
      {
        title: "会话与模型",
        commands: [
          { cmd: "/clear", desc: "清空聊天历史，但保留当前文件选择", example: "/clear" },
          { cmd: "/reset", desc: "清空历史并移除所有文件，相当于从头开始", example: "/reset" },
          { cmd: "/model", desc: "切换主模型", example: "/model openai/gpt-4.1" },
          { cmd: "/models", desc: "搜索可用模型列表", example: "/models claude" },
          { cmd: "/reasoning-effort", desc: "设置推理强度，取值随模型不同而不同", example: "/reasoning-effort high" },
          { cmd: "/tokens", desc: "查看当前聊天上下文用了多少 token", example: "/tokens" },
          { cmd: "/web", desc: "抓取网页并转成 Markdown 发进聊天", example: "/web https://example.com/docs" },
          { cmd: "/quit", desc: "退出 aider；/exit 同义", example: "/quit" },
        ],
      },
    ],
  },
  {
    id: "windsurf",
    name: "Windsurf",
    subtitle: "带 Cascade agent 的 AI 编程编辑器",
    docsUrl: "https://docs.windsurf.com/windsurf/cascade",
    icon: "/ui-new/tool-icons/windsurf.png",
    sections: [
      {
        title: "Cascade 上下文",
        commands: [
          { cmd: "@ Mentions", desc: "在 Cascade 输入框里用 @ 引入文件、目录、命令输出、网页或其他上下文", example: "@src/lib/api.ts 解释这里的数据流" },
          { cmd: "Memories", desc: "让 Cascade 自动保存跨会话长期上下文，比如项目习惯和常用决策", example: "让 Cascade 记住本项目默认用 dim 主题" },
          { cmd: "Rules", desc: "用全局、工作区或系统级规则约束 Cascade 的代码风格和项目要求", example: ".windsurf/rules/*.md" },
          { cmd: "Workflows", desc: "把常见流程做成可复用步骤，适合固定的测试、发布或排障动作", example: "Run release checklist" },
          { cmd: "Skills", desc: "把更复杂的任务能力封装成可复用技能，让 Cascade 按专门流程工作", example: "Use project skill" },
        ],
      },
      {
        title: "终端与编辑",
        commands: [
          { cmd: "Terminal", desc: "Windsurf 终端可结合 Cascade 理解当前 shell 和命令输出", example: "解释刚才测试失败的原因" },
          { cmd: "Command Palette", desc: "通过命令面板触发编辑器动作、设置和 Cascade 相关功能", example: "Ctrl/Cmd + Shift + P" },
          { cmd: "Inline Edit", desc: "在编辑器里选中代码后直接让 AI 改写、解释或修复", example: "选中函数后让 Cascade 简化逻辑" },
          { cmd: "Cascade Chat", desc: "用侧边栏对话驱动多文件分析、改动和调试", example: "修复这个页面的移动端溢出" },
        ],
      },
      {
        title: "规则文件",
        commands: [
          { cmd: "Global rules", desc: "用户级规则，适合个人偏好；会影响多个工作区", example: "global_rules.md" },
          { cmd: "Workspace rules", desc: "项目级规则，适合写技术栈、目录约束和提交习惯", example: ".windsurf/rules/project.md" },
          { cmd: "System rules", desc: "企业管理员可下发系统级规则，普通用户不能删除", example: "C:\\ProgramData\\Windsurf\\rules\\*.md" },
          { cmd: "trigger / globs", desc: "在规则 frontmatter 中设置触发方式，只在匹配文件或场景下启用", example: "trigger: glob" },
        ],
      },
    ],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    subtitle: "GitHub 官方 AI 编程助手与 CLI",
    docsUrl: "https://docs.github.com/zh/copilot/reference/chat-cheat-sheet",
    icon: "/ui-new/tool-icons/github-copilot.png",
    sections: [
      {
        title: "Copilot Chat 斜杠命令",
        commands: [
          { cmd: "/explain", desc: "解释当前编辑器里的代码或选中代码", example: "/explain" },
          { cmd: "/fix", desc: "针对选中代码或错误提出修复方案", example: "/fix" },
          { cmd: "/tests", desc: "为选中的代码生成单元测试", example: "/tests" },
          { cmd: "/doc", desc: "为当前符号生成文档注释", example: "/doc" },
          { cmd: "/optimize", desc: "分析并改善选中代码的运行效率；在部分环境可用", example: "/optimize" },
          { cmd: "/simplify", desc: "简化当前代码选择；在 Xcode 等环境可用", example: "/simplify" },
          { cmd: "/help", desc: "显示 Copilot Chat 的基础用法和快速参考", example: "/help" },
        ],
      },
      {
        title: "上下文引用",
        commands: [
          { cmd: "#file", desc: "把当前文件内容加入提示词上下文", example: "解释 #file 里的缓存逻辑" },
          { cmd: "#selection", desc: "引用当前选中的文本", example: "给 #selection 补测试" },
          { cmd: "#function / #class", desc: "引用当前函数或类，适合精确讨论一段代码", example: "重构 #function" },
          { cmd: "#project", desc: "引入项目上下文，让 Copilot 从项目整体理解问题", example: "#project 里哪里处理鉴权" },
          { cmd: "@workspace", desc: "让 Copilot 结合工作区代码结构回答", example: "@workspace 这个接口在哪里被调用" },
          { cmd: "@terminal", desc: "引用 VS Code 终端上下文，适合解释命令或报错", example: "@terminal 这个构建失败怎么修" },
          { cmd: "@github", desc: "调用 GitHub 相关能力，比如仓库、PR、issue 等上下文", example: "@github 总结这个 PR" },
        ],
      },
      {
        title: "Copilot CLI",
        commands: [
          { cmd: "copilot", desc: "启动 Copilot CLI 交互式界面", example: "copilot" },
          { cmd: 'copilot --prompt "..."', desc: "从命令行直接给 Copilot 一条提示词", example: 'copilot --prompt "解释这个错误"' },
          { cmd: "copilot resume", desc: "恢复以前的 CLI 会话", example: "copilot resume" },
          { cmd: "copilot mcp", desc: "配置或管理 MCP server", example: "copilot mcp list" },
          { cmd: "copilot init", desc: "初始化项目级 Copilot 指令文件", example: "copilot init" },
          { cmd: "/review", desc: "在交互界面中审查当前改动", example: "/review" },
          { cmd: "/model", desc: "在交互界面里切换模型", example: "/model" },
        ],
      },
    ],
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    subtitle: "开源多通道 agent 运行时与 CLI",
    docsUrl: "https://docs.openclaw.ai/cli",
    icon: "/ui-new/tool-icons/openclaw.png",
    sections: [
      {
        title: "基础与服务",
        commands: [
          { cmd: "openclaw status", desc: "查看本机 OpenClaw 状态；加 --usage 可看供应商用量和额度", example: "openclaw status --usage" },
          { cmd: "openclaw health", desc: "检查服务健康状态", example: "openclaw health" },
          { cmd: "openclaw setup", desc: "初始化或配置本地 OpenClaw 环境", example: "openclaw setup" },
          { cmd: "openclaw update", desc: "更新 OpenClaw", example: "openclaw update" },
          { cmd: "openclaw daemon start", desc: "启动后台守护进程", example: "openclaw daemon start" },
          { cmd: "openclaw gateway restart", desc: "重启 gateway 服务", example: "openclaw gateway restart" },
          { cmd: "openclaw logs", desc: "查看运行日志", example: "openclaw logs" },
          { cmd: "openclaw doctor", desc: "执行诊断，排查环境和配置问题", example: "openclaw doctor" },
        ],
      },
      {
        title: "Agent、会话与模型",
        commands: [
          { cmd: "openclaw agent", desc: "进入或管理单个 agent 相关能力", example: "openclaw agent" },
          { cmd: "openclaw agents list", desc: "列出已配置 agent", example: "openclaw agents list" },
          { cmd: "openclaw sessions cleanup", desc: "清理会话数据", example: "openclaw sessions cleanup" },
          { cmd: "openclaw tasks list", desc: "查看任务列表", example: "openclaw tasks list" },
          { cmd: "openclaw models list", desc: "列出可用模型", example: "openclaw models list" },
          { cmd: "openclaw models set <model>", desc: "设置当前默认模型", example: "openclaw models set gpt-5.1-codex" },
          { cmd: "openclaw infer web search", desc: "通过 inference 能力执行网页搜索", example: "openclaw infer web search \"Astro 5 docs\"" },
          { cmd: "openclaw mcp list", desc: "查看 MCP 配置", example: "openclaw mcp list" },
        ],
      },
      {
        title: "Chat 斜杠命令",
        commands: [
          { cmd: "/status", desc: "快速查看会话诊断信息", example: "/status" },
          { cmd: "/trace", desc: "查看当前会话的插件 trace/debug 信息", example: "/trace" },
          { cmd: "/config", desc: "修改并持久化配置", example: "/config" },
          { cmd: "/debug", desc: "设置仅运行期生效的调试覆盖项；需要启用 commands.debug", example: "/debug" },
        ],
      },
      {
        title: "工具与自动化",
        commands: [
          { cmd: "openclaw cron list", desc: "列出定时任务", example: "openclaw cron list" },
          { cmd: "openclaw cron add", desc: "添加定时任务", example: "openclaw cron add" },
          { cmd: "openclaw approvals get", desc: "查看审批策略", example: "openclaw approvals get" },
          { cmd: "openclaw browser screenshot", desc: "通过浏览器工具截图", example: "openclaw browser screenshot" },
          { cmd: "openclaw hooks list", desc: "列出 hooks", example: "openclaw hooks list" },
          { cmd: "openclaw skills", desc: "管理 skills", example: "openclaw skills" },
          { cmd: "openclaw plugins", desc: "管理 plugins", example: "openclaw plugins" },
          { cmd: "openclaw tui", desc: "启动 TUI；chat 和 terminal 是本地 TUI 别名", example: "openclaw tui" },
        ],
      },
    ],
  },
  {
    id: "hermes",
    name: "Hermes",
    subtitle: "Nous Research 的跨渠道 AI agent",
    docsUrl: "https://hermes-agent.nousresearch.com/docs/reference/cli-commands",
    icon: "/ui-new/tool-icons/hermes.png",
    sections: [
      {
        title: "CLI 入口与维护",
        commands: [
          { cmd: "hermes [global-options] <command>", desc: "Hermes 的全局入口，所有终端命令都从这里开始", example: "hermes chat" },
          { cmd: "hermes chat", desc: "启动本地聊天会话；也可配合 profile 使用", example: "hermes -p work chat" },
          { cmd: 'hermes -z "<prompt>"', desc: "脚本化一次性运行提示词，适合自动化和命令行串联", example: 'hermes -z "summarize this repo"' },
          { cmd: "hermes model", desc: "管理模型供应商、模型和认证", example: "hermes model" },
          { cmd: "hermes setup", desc: "初始化 Hermes 环境", example: "hermes setup" },
          { cmd: "hermes doctor", desc: "诊断本地安装、配置和依赖问题", example: "hermes doctor" },
          { cmd: "hermes status", desc: "查看服务和会话状态", example: "hermes status" },
          { cmd: "hermes update --check", desc: "检查是否有新版本，不执行安装", example: "hermes update --check" },
          { cmd: "hermes completion [bash|zsh|fish]", desc: "输出 shell 补全脚本", example: "hermes completion zsh" },
        ],
      },
      {
        title: "会话斜杠命令",
        commands: [
          { cmd: "/new", desc: "开启新对话", example: "/new" },
          { cmd: "/reset", desc: "重置会话历史", example: "/reset" },
          { cmd: "/clear", desc: "清屏并开始新会话；会丢掉当前内存中的会话状态", example: "/clear --yes" },
          { cmd: "/resume [name]", desc: "恢复之前命名过的会话", example: "/resume login-fix" },
          { cmd: "/title [name]", desc: "设置或查看会话标题", example: "/title 支付重构" },
          { cmd: "/compress [focus topic]", desc: "手动压缩上下文，可指定要重点保留的主题", example: "/compress 保留后端接口约束" },
          { cmd: "/undo", desc: "移除最近一轮用户和助手交换", example: "/undo -y" },
          { cmd: "/quit", desc: "退出当前 CLI 会话", example: "/quit" },
        ],
      },
      {
        title: "模型、工具与运行模式",
        commands: [
          { cmd: "/model [provider:model]", desc: "显示或切换当前模型；--global 可写入 config.yaml", example: "/model fav --global" },
          { cmd: "/fast [normal|fast|status]", desc: "切换快速模式，比如 OpenAI Priority Processing 或 Anthropic Fast Mode", example: "/fast status" },
          { cmd: "/reasoning [level|show|hide]", desc: "调整推理强度或控制推理展示", example: "/reasoning high" },
          { cmd: "/reload-mcp", desc: "重新加载 MCP server；/reload_mcp 也是别名", example: "/reload-mcp" },
          { cmd: "/yolo", desc: "切换 YOLO 模式，会跳过危险命令审批，谨慎使用", example: "/yolo" },
          { cmd: "/approve [session|always]", desc: "批准待执行的危险命令，本次批准或永久加入允许列表", example: "/approve session" },
          { cmd: "/deny", desc: "拒绝待执行的危险命令", example: "/deny" },
        ],
      },
      {
        title: "后台与多渠道",
        commands: [
          { cmd: "/background <prompt>", desc: "把任务放到独立后台会话执行，完成后把结果发回当前聊天", example: "/background 跑完测试并修复失败项" },
          { cmd: "/queue <prompt>", desc: "把下一条提示排队；/q 是别名", example: "/q 等当前任务结束后跑 lint" },
          { cmd: "/steer <prompt>", desc: "在下一次工具调用后注入指导，不打断当前 agent", example: "/steer 只改前端文件" },
          { cmd: "/goal <text>", desc: "设置持续目标，Hermes 会跨轮推进直到达成、暂停或到达预算", example: "/goal 所有测试通过" },
          { cmd: "/voice [on|off|tts|join|status]", desc: "控制语音回复；Discord 下还支持加入或离开语音频道", example: "/voice status" },
          { cmd: "/kanban <action>", desc: "从聊天里操作协作看板，和 CLI 参数面一致", example: "/kanban list --mine" },
          { cmd: "/commands [page]", desc: "分页浏览所有命令和 skills", example: "/commands 2" },
          { cmd: "/help", desc: "显示消息平台里的帮助说明", example: "/help" },
        ],
      },
    ],
  },
];

